version: '3.8'

services:
  gateway:
    image: micorservice-gateway:latest
    container_name: gateway
    ports:
      - "8081:8081"
    environment:
      - SERVER_EUREKA=localhost:8761
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  eureka-server:
    image: msvc-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
