server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: ${RENDER_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://${RENDER_HOSTNAME}:${server.port}/eureka